/* **************************************************************************
	
	Create Database for Legend of Mir 2

	All written by Euy-heon, Jeong
	Copyright (C) 2001 Wemade Entertainment. All rights reserved.

   *************************************************************************** */

USE LEGENDOFMIR
GO

DROP TABLE TBL_CHARACTER_MAGIC
GO

/* 
	User Character Magic Table
*/

CREATE TABLE TBL_CHARACTER_MAGIC
(
	FLD_LOGINID		CHAR(10)		NOT NULL,
	FLD_CHARNAME		CHAR(20)		NOT NULL,

	FLD_LEVEL0		TINYINT			DEFAULT(0),
	FLD_USEKEY0		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN0		INT			DEFAULT(0),

	FLD_LEVEL1		TINYINT			DEFAULT(0),
	FLD_USEKEY1		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN1		INT			DEFAULT(0),

	FLD_LEVEL2		TINYINT			DEFAULT(0),
	FLD_USEKEY2		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN2		INT			DEFAULT(0),

	FLD_LEVEL3		TINYINT			DEFAULT(0),
	FLD_USEKEY3		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN3		INT			DEFAULT(0),

	FLD_LEVEL4		TINYINT			DEFAULT(0),
	FLD_USEKEY4		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN4		INT			DEFAULT(0),

	FLD_LEVEL5		TINYINT			DEFAULT(0),
	FLD_USEKEY5		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN5		INT			DEFAULT(0),

	FLD_LEVEL6		TINYINT			DEFAULT(0),
	FLD_USEKEY6		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN6		INT			DEFAULT(0),

	FLD_LEVEL7		TINYINT			DEFAULT(0),
	FLD_USEKEY7		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN7		INT			DEFAULT(0),

	FLD_LEVEL8		TINYINT			DEFAULT(0),
	FLD_USEKEY8		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN8		INT			DEFAULT(0),

	FLD_LEVEL9		TINYINT			DEFAULT(0),
	FLD_USEKEY9		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN9		INT			DEFAULT(0),

	FLD_LEVEL10		TINYINT			DEFAULT(0),
	FLD_USEKEY10		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN10		INT			DEFAULT(0),

	FLD_LEVEL11		TINYINT			DEFAULT(0),
	FLD_USEKEY11		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN11		INT			DEFAULT(0),

	FLD_LEVEL12		TINYINT			DEFAULT(0),
	FLD_USEKEY12		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN12		INT			DEFAULT(0),

	FLD_LEVEL13		TINYINT			DEFAULT(0),
	FLD_USEKEY13		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN13		INT			DEFAULT(0),

	FLD_LEVEL14		TINYINT			DEFAULT(0),
	FLD_USEKEY14		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN14		INT			DEFAULT(0),

	FLD_LEVEL15		TINYINT			DEFAULT(0),
	FLD_USEKEY15		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN15		INT			DEFAULT(0),

	FLD_LEVEL16		TINYINT			DEFAULT(0),
	FLD_USEKEY16		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN16		INT			DEFAULT(0),

	FLD_LEVEL17		TINYINT			DEFAULT(0),
	FLD_USEKEY17		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN17		INT			DEFAULT(0),

	FLD_LEVEL18		TINYINT			DEFAULT(0),
	FLD_USEKEY18		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN18		INT			DEFAULT(0),

	FLD_LEVEL19		TINYINT			DEFAULT(0),
	FLD_USEKEY19		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN19		INT			DEFAULT(0),

	FLD_LEVEL20		TINYINT			DEFAULT(0),
	FLD_USEKEY20		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN20		INT			DEFAULT(0),

	FLD_LEVEL21		TINYINT			DEFAULT(0),
	FLD_USEKEY21		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN21		INT			DEFAULT(0),

	FLD_LEVEL22		TINYINT			DEFAULT(0),
	FLD_USEKEY22		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN22		INT			DEFAULT(0),

	FLD_LEVEL23		TINYINT			DEFAULT(0),
	FLD_USEKEY23		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN23		INT			DEFAULT(0),

	FLD_LEVEL24		TINYINT			DEFAULT(0),
	FLD_USEKEY24		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN24		INT			DEFAULT(0),

	FLD_LEVEL25		TINYINT			DEFAULT(0),
	FLD_USEKEY25		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN25		INT			DEFAULT(0),

	FLD_LEVEL26		TINYINT			DEFAULT(0),
	FLD_USEKEY26		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN26		INT			DEFAULT(0),

	FLD_LEVEL27		TINYINT			DEFAULT(0),
	FLD_USEKEY27		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN27		INT			DEFAULT(0),

	FLD_LEVEL28		TINYINT			DEFAULT(0),
	FLD_USEKEY28		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN28		INT			DEFAULT(0),

	FLD_LEVEL29		TINYINT			DEFAULT(0),
	FLD_USEKEY29		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN29		INT			DEFAULT(0),

	FLD_LEVEL30		TINYINT			DEFAULT(0),
	FLD_USEKEY30		TINYINT			DEFAULT(0),
	FLD_CURRTRAIN30		INT			DEFAULT(0),

)
GO

ALTER TABLE TBL_CHARACTER_MAGIC ADD CONSTRAINT PK_CHARACTER_MAGIC  PRIMARY KEY (FLD_LOGINID, FLD_CHARNAME)
GO
