USE MASTER
GO

IF NOT EXISTS (SELECT * FROM SYSUSERS WHERE NAME = 'MIR_DBA')
	SP_ADDUSER 'MIR_DBA'
	GO
	
	SP_ADDUSER 'MIR_USER_0'	
	GO
	SP_ADDUSER 'MIR_USER_1'	
	GO
	SP_ADDUSER 'MIR_USER_2'	
	GO
	SP_ADDUSER 'MIR_USER_3'	
	GO
	SP_ADDUSER 'MIR_USER_4'	
	GO
	SP_ADDUSER 'MIR_USER_5'	
	GO
	SP_ADDUSER 'MIR_USER_6'
	GO
	SP_ADDUSER 'MIR_USER_7'
	GO
	SP_ADDUSER 'MIR_USER_8'
	GO
	SP_ADDUSER 'MIR_USER_9'
	GO

	GRANT ALL ON TBL_ACCOUNT TO MIR_DBA
END IF