//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SelGate.rc
//
#define IDS_NOTWINNT                    1
#define IDS_LVS_LABEL1                  2
#define IDS_LVS_LABEL2                  3
#define IDS_LVS_LABEL3                  4
#define IDS_STARTSERVICE                5
#define IDS_STOPSERVICE                 6
#define IDS_CONNECT_LOGINSERVER         7
#define IDS_DISCONNECT_LOGINSERVER      8
#define IDS_PROGRAM_QUIT                9
#define IDS_PROGRAM_TITLE               10
#define IDS_CANT_CONNECT                11
#define IDS_APPLY_RECONNECT             12
#define IDD_DIALOG1                     101
#define IDR_MAINMENU                    101
#define IDM_FONTCOLOR                   101
#define IDI_MIR2                        102
#define IDM_BACKCOLOR                   102
#define IDB_TOOLBAR                     103
#define IDD_CONFIGDLG                   104
#define IDC_LOGINSVR_IP                 1003
#define IDC_LOGINSVR_PORT               1004
#define IDC_LOCALPORT                   1005
#define IDC_EDIT1                       1006
#define IDM_STARTSERVICE                40001
#define IDM_STOPSERVICE                 40002
#define IDM_CONFIG                      40003
#define IDM_EXIT                        40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
