//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GameGate.rc
//
#define IDS_NOTWINNT                    1
#define IDC_MYICON                      2
#define IDS_LVS_LABEL1                  2
#define IDS_LVS_LABEL2                  3
#define IDS_LVS_LABEL3                  4
#define IDS_STARTSERVICE                5
#define IDS_STOPSERVICE                 6
#define IDS_CONNECT_LOGINSERVER         7
#define IDS_DISCONNECT_LOGINSERVER      8
#define IDS_PROGRAM_QUIT                9
#define IDS_PROGRAM_TITLE               10
#define IDS_CANT_CONNECT                11
#define IDS_APPLY_RECONNECT             12
#define IDS_LOAD_ABUSIVE                13
#define IDS_LOADFAIL_ABUSIVE            14
#define IDR_MAINMENU                    101
#define IDD_GAMEGATE_DIALOG             102
#define IDI_MIR2                        102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDB_TOOLBAR                     103
#define IDM_ABOUT                       104
#define IDD_CONFIGDLG                   104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_GAMEGATE                    107
#define IDI_SMALL                       108
#define IDC_GAMEGATE                    109
#define IDR_MAINFRAME                   128
#define IDC_LOGINSVR_IP                 1003
#define IDC_LOGINSVR_PORT               1004
#define IDC_LOCALPORT                   1005
#define IDC_SERVERINDEX                 1006
#define IDM_STARTSERVICE                40001
#define IDM_STOPSERVICE                 40002
#define IDM_CONFIG                      40003
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
