//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GameSvr.rc
//
#define IDS_NOTWINNT                    1
#define IDS_LVS_LABEL1                  2
#define IDS_LVS_LABEL2                  3
#define IDS_LVS_LABEL3                  4
#define IDS_STARTSERVICE                5
#define IDS_STOPSERVICE                 6
#define IDS_CONNECT_LOGINSERVER         7
#define IDS_FETCH_MAGICDATA             7
#define IDS_DISCONNECT_LOGINSERVER      8
#define IDS_PROGRAM_QUIT                9
#define IDS_PROGRAM_TITLE               10
#define IDS_LOAD_ADMINCOMMAND           11
#define IDS_CONFLVS_LABEL1              12
#define IDS_CONFLVS_LABEL2              13
#define IDS_CONFLVS_LABEL3              14
#define IDS_CONFLVS_LABEL4              15
#define IDS_CONFLVS_LABEL5              16
#define IDS_TAB_LABEL1                  17
#define IDS_ACCEPT_GATESERVER           18
#define IDS_OPEN_USER                   19
#define IDS_CLOSE_USER                  20
#define IDS_OPEN_GATE                   21
#define IDS_CLOSE_GATE                  22
#define IDS_CONNECT_DBSERVER            76
#define IDS_LOADMAPFILE_GOOD            97
#define IDS_LOADMAPFILE_FAIL            98
#define IDS_DISCONNECT_DBSERVER         99
#define IDS_APPLY_RECONNECT             100
#define IDS_CANT_CONNECT                101
#define IDS_FETCH_MONSTER               102
#define IDS_FETCH_MONGEN                103
#define IDS_FETCH_STDITEMWEAPON         104
#define IDS_FETCH_STDITEMARMOR          105
#define IDS_FETCH_MERCHANT              106
#define IDS_FETCH_MOVEMAPEVENT          107
#define IDS_ALLOW_LONGHIT               108
#define IDS_NOTALLOW_LONGHIT            109
#define IDS_ALLOW_WIDEHIT               110
#define IDS_NOTALLOW_WIDEHIT            111
#define IDS_ALLOW_FIREHIT               112
#define IDS_NOTALLOW_FIREHIT            113
#define IDS_TIMEOUT_FIREHIT             114
#define IDS_ATTACKMODE_ALL              115
#define IDS_ATTACKMODE_PEACE            116
#define IDI_MIR2                        117
#define IDR_MAINMENU                    118
#define IDS_ATTACKMODE_GROUP            119
#define IDB_TOOLBAR                     120
#define IDS_ATTACKMODE_GUILD            121
#define IDS_ATTACKMODE_PKATTACK         122
#define IDD_CONFIGDLG                   123
#define IDS_ATTACKMODE_CHGMODE          124
#define IDS_NOTENOUGH_MANA              125
#define IDS_FETCH_STDITEMETC            126
#define IDS_FETCH_STDITEMACCESSORY      127
#define IDS_JOBNAME_W                   128
#define IDS_JOBNAME_S                   129
#define IDS_JOBNAME_T                   130
#define IDS_INSPECTOR_ON                131
#define IDS_INSPECTOR_OFF               132
#define IDS_NOTENOUGHLEVEL_CRY          133
#define IDS_CANTFIND_HUMAN              134
#define IDS_SKIL_LEVELUP                135
#define IDS_USERCMD_NOWHISPER1          136
#define IDS_USERCMD_NOWHISPER2          137
#define IDS_USERCMD_YESWHISPER1         138
#define IDS_USERCMD_YESWHISPER2         139
#define IDS_USERCMD_NOWHISPER_SOMEBODY  140
#define IDS_USERCMD_DONTCRY1            141
#define IDS_USERCMD_DONTCRY2            142
#define IDS_USERCMD_DONTEXNG            143
#define IDS_USERCMD_ACPTGUILD           144
#define IDS_USERCMD_ALOWPARTY           145
#define IDS_USERCMD_DOPARTY             146
#define IDS_USERCMD_BROKEPARTY          147
#define IDS_USERCMD_OUTGUILD            148
#define IDS_USERCMD_NOGUILDCRY1         149
#define IDS_USERCMD_NOGUILDCRY2         150
#define IDS_USERCMD_ATTACKMODE          151
#define IDS_USERCMD_REST                152
#define IDS_USERCMD_SABUKDOOR           153
#define IDS_LOAD_USERCOMMAND            154
#define IDS_DEFENCEUP                   155
#define IDS_MAGDEFENCEUP                156
#define IDS_TRANSGENDER                 157
#define IDS_MALE_WEAR                   158
#define IDS_FEMALE_WEAR                 159
#define IDS_NOTENOUGH_VALUE             160
#define IDS_NOTENOUGH_WEIGHT            161
#define IDS_GOLD                        162
#define IDS_NEVERDIE_ON                 163
#define IDS_NEVERDIE_OFF                164
#define IDS_CAPTURE_ON                  165
#define IDS_CAPTURE_OFF                 166
#define IDC_SRVINDEX                    1000
#define IDC_STARTLEVEL                  1001
#define IDC_STARTGOLD                   1002
#define IDC_DBSVR_IP                    1003
#define IDC_DBSRV_PORT                  1004
#define IDC_CHECK_TESTSRV               1005
#define IDC_SRVNUMBER                   1006
#define IDC_SRVNAME                     1007
#define IDC_DBMS_IP                     1008
#define IDC_MAPFILE_LOC                 1009
#define IDC_DBMS_PORT                   1010
#define IDC_DBMS_ID                     1011
#define IDC_DBMS_PASSWORD               1012
#define IDC_DBMS_DEVICE                 1013
#define IDM_STARTSERVICE                40001
#define IDM_STOPSERVICE                 40002
#define IDM_CONFIG                      40003
#define IDM_EXIT                        40004
#define IDM_SHOW_READYUSERLIST          40005
#define IDM_SETBKGCOLOR                 40006
#define IDM_SETFONTCOLOR                40007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           164
#endif
#endif
